# Generated by Django 5.2.4 on 2025-08-06 07:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('generator', models.CharField(max_length=100, verbose_name='제작자')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('link', models.URLField(max_length=800, verbose_name='링크')),
                ('language', models.CharField(max_length=10, verbose_name='언어')),
                ('web_master', models.EmailField(max_length=100, verbose_name='웹 마스터')),
                ('copyright', models.CharField(max_length=1000, verbose_name='저작권')),
                ('last_build_date', models.DateTimeField(verbose_name='마지막 빌드 날짜')),
                ('description', models.TextField(verbose_name='설명')),
                ('image_title', models.CharField(max_length=500, verbose_name='이미지 제목')),
                ('image_url', models.URLField(max_length=800, verbose_name='이미지 링크')),
                ('image_link', models.URLField(max_length=800, verbose_name='이미지 링크')),
                ('image_height', models.IntegerField(verbose_name='이미지 높이')),
                ('image_width', models.IntegerField(verbose_name='이미지 너비')),
            ],
            options={
                'verbose_name': '뉴스 채널',
                'verbose_name_plural': '뉴스 채널',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(max_length=50, unique=True, verbose_name='이메일')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='이름')),
                ('address', models.CharField(blank=True, max_length=20, null=True, verbose_name='주소')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('link', models.URLField(max_length=1000, verbose_name='링크')),
                ('guid', models.CharField(max_length=700, verbose_name='GUID')),
                ('pub_date', models.DateTimeField(verbose_name='게시 날짜')),
                ('description', models.TextField(verbose_name='설명')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='신문사 이름')),
                ('source_url', models.URLField(blank=True, max_length=100, null=True, verbose_name='신문사 사이트')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newschannel', verbose_name='뉴스 채널')),
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '블로그',
                'verbose_name_plural': '블로그',
            },
        ),
    ]
