# Request Vision API: https://learn.microsoft.com/ko-kr/azure/ai-services/computer-vision/how-to/call-analyze-image-40?tabs=csharp&pivots=programming-language-rest-api
# using local image file
POST {{$dotenv AZURE_VISION_ENDPOINT_URL}}/computervision/imageanalysis:analyze
     ?api-version=2024-02-01
     &features=tags,read,caption,denseCaptions,smartCrops,objects,people
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_VISION_API_KEY}}
Content-Type: application/octet-stream

< ./data/images/ImageTaggingSample1-fd324157.jpg

###

# gender-neutral-caption
POST {{$dotenv AZURE_VISION_ENDPOINT_URL}}/computervision/imageanalysis:analyze
     ?api-version=2024-02-01
     &features=caption
     &gender-neutral-caption=true
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_VISION_API_KEY}}
Content-Type: application/json

{
    "url": "https://learn.microsoft.com/en-us/azure/cognitive-services/computer-vision/images/windows-kitchen.jpg"
}

# using image url
POST {{$dotenv AZURE_VISION_ENDPOINT_URL}}/computervision/imageanalysis:analyze
     ?api-version=2024-02-01
     &features=tags,read,caption,denseCaptions,smartCrops,objects,people
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_VISION_API_KEY}}
Content-Type: application/json

{
    "url": "https://learn.microsoft.com/en-us/azure/cognitive-services/computer-vision/images/windows-kitchen.jpg"
}

###

# using image url
POST {{$dotenv AZURE_VISION_ENDPOINT_URL}}/computervision/imageanalysis:analyze
     ?api-version=2024-02-01
     &features=tags
     &language=ko
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_VISION_API_KEY}}
Content-Type: application/json

{
    "url": "https://learn.microsoft.com/en-us/azure/cognitive-services/computer-vision/images/windows-kitchen.jpg"
}

###

# smart crops
POST	{{$dotenv AZURE_VISION_ENDPOINT_URL}}/computervision/imageanalysis:analyze
     ?api-version=2024-02-01
     &features=SmartCrops
     &model-version=latest
     &language=en
     &smartcrops-aspect-ratios=1.25,0.75
     &gender-neutral-caption=false
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_VISION_API_KEY}}
Content-Type: application/json

{
    "url": "https://learn.microsoft.com/en-us/azure/cognitive-services/computer-vision/images/windows-kitchen.jpg"
}

###

# Request Face API: https://learn.microsoft.com/ko-kr/azure/ai-services/computer-vision/quickstarts-sdk/identity-client-library?tabs=linux%2Cvisual-studio&pivots=programming-language-rest-api
POST {{$dotenv AZURE_FACE_ENDPOINT_URL}}/face/v1.0/detect
     ?returnFaceId=false
     &returnFaceLandmarks=true
     &returnFaceAttributes=mask
     &recognitionModel=recognition_04
     &returnRecognitionModel=false
     &detectionModel=detection_03
     &faceIdTimeToLive=86400
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_FACE_API_KEY}}
Content-Type: application/json

{
    "url": "https://portal.vision.cognitive.azure.com/dist/assets/face-detection-demo3-567ebb5e.png"
}
