###

# Request PII Detection Docs: https://learn.microsoft.com/ko-kr/azure/ai-services/language-service/personally-identifiable-information/quickstart?pivots=rest-api&tabs=linux#send-a-personally-identifying-information-pii-detection-api-request
POST {{$dotenv AZURE_LANGUAGE_ENDPOINT_URL}}/language/:analyze-text
     ?api-version=2022-05-01
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_LANGUAGE_API_KEY}}

{
    "kind": "PiiEntityRecognition",
    "parameters": {
        "modelVersion": "latest"
    },
    "analysisInput":{
        "documents":[
            {
                "id":"1",
                "language": "en",
                "text": "안녕하세요, 제 이름은 김민수입니다. 저는 서울특별시 강남구 테헤란로 123, 4층에 위치한 ABC 회사에서 일하고 있습니다. 제 전화번호는 010-1234-5678이며, 이메일 주소는 minsu.kim@email.com입니다. 저희 회사의 대표 전화번호는 02-9876-5432입니다. 저는 1985년 3월 15일에 태어났고, 현재 38세입니다. 제 가족은 아내와 두 아이가 있습니다. 아내의 이름은 이영희이고, 그녀는 대학교에서 심리학을 전공했습니다. 아이들은 각각 7세와 5세이며, 학교에 다니고 있습니다. 저희 집 주소는 서울특별시 송파구 잠실동 456-78입니다. 최근에 저는 건강 검진을 받았고, 그 결과 고혈압 진단을 받았습니다. 이로 인해 주치의는 저에게 정기적인 운동과 건강한 식습관을 유지할 것을 권장했습니다. 주치의의 이름은 박지훈이며, 그의 병원은 서울 강서구에 위치한 강서메디컬입니다. 저는 여행을 좋아해서 매년 가족과 함께 해외여행을 계획합니다. 지난 여름에는 일본 도쿄에 갔었고, 그곳에서 가족과 함께 디즈니랜드를 방문했습니다. 그 여행에서 찍은 사진은 제 개인 소셜 미디어 계정에 업로드했습니다. 저는 IT 관련 분야에서 경력을 쌓아왔고, 현재 데이터 분석가로 일하고 있습니다. 제 직무는 데이터 수집, 분석 및 보고서를 작성하는 것입니다. 최근 프로젝트는 고객 행동 분석에 관한 것이며, 이를 통해 마케팅 전략을 개선하고 있습니다. 마지막으로, 저는 올해 새로운 기술을 배우기 위해 온라인 강좌에 등록했습니다. 관심 있는 분야는 인공지능과 머신러닝이며, 이를 통해 제 커리어를 발전시키고자 합니다."
            }
        ]
    }
}

###

# Request named entity recognition Docs: https://learn.microsoft.com/ko-kr/azure/ai-services/language-service/named-entity-recognition/quickstart?tabs=linux%2Cga-api&pivots=rest-api#send-a-named-entity-recognition-api-request
POST {{$dotenv AZURE_LANGUAGE_ENDPOINT_URL}}/language/:analyze-text
     ?api-version=2022-05-01
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_LANGUAGE_API_KEY}}

{
    "kind": "EntityRecognition",
    "parameters": {
        "modelVersion": "latest"
    },
    "analysisInput":{
        "documents":[
            {
                "id":"1",
                "language": "en",
                "text": "안녕하세요, 제 이름은 김민수입니다. 저는 서울특별시 강남구 테헤란로 123, 4층에 위치한 ABC 회사에서 일하고 있습니다. 제 전화번호는 010-1234-5678이며, 이메일 주소는 minsu.kim@email.com입니다. 저희 회사의 대표 전화번호는 02-9876-5432입니다. 저는 1985년 3월 15일에 태어났고, 현재 38세입니다. 제 가족은 아내와 두 아이가 있습니다. 아내의 이름은 이영희이고, 그녀는 대학교에서 심리학을 전공했습니다. 아이들은 각각 7세와 5세이며, 학교에 다니고 있습니다. 저희 집 주소는 서울특별시 송파구 잠실동 456-78입니다. 최근에 저는 건강 검진을 받았고, 그 결과 고혈압 진단을 받았습니다. 이로 인해 주치의는 저에게 정기적인 운동과 건강한 식습관을 유지할 것을 권장했습니다. 주치의의 이름은 박지훈이며, 그의 병원은 서울 강서구에 위치한 강서메디컬입니다. 저는 여행을 좋아해서 매년 가족과 함께 해외여행을 계획합니다. 지난 여름에는 일본 도쿄에 갔었고, 그곳에서 가족과 함께 디즈니랜드를 방문했습니다. 그 여행에서 찍은 사진은 제 개인 소셜 미디어 계정에 업로드했습니다. 저는 IT 관련 분야에서 경력을 쌓아왔고, 현재 데이터 분석가로 일하고 있습니다. 제 직무는 데이터 수집, 분석 및 보고서를 작성하는 것입니다. 최근 프로젝트는 고객 행동 분석에 관한 것이며, 이를 통해 마케팅 전략을 개선하고 있습니다. 마지막으로, 저는 올해 새로운 기술을 배우기 위해 온라인 강좌에 등록했습니다. 관심 있는 분야는 인공지능과 머신러닝이며, 이를 통해 제 커리어를 발전시키고자 합니다."
            }
        ]
    }
}

###

# Request text analytics for health Docs: https://learn.microsoft.com/ko-kr/azure/ai-services/language-service/text-analytics-for-health/quickstart?tabs=linux&pivots=rest-api#text-analytics-for-health
POST {{$dotenv AZURE_LANGUAGE_ENDPOINT_URL}}/language/analyze-text/jobs
     ?api-version=2024-11-15-preview
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_LANGUAGE_API_KEY}}

{
    "analysisInput": {
        "documents": [
            {
                "text": "안녕하세요, 제 이름은 김민수입니다. 저는 서울특별시 강남구 테헤란로 123, 4층에 위치한 ABC 회사에서 일하고 있습니다. 제 전화번호는 010-1234-5678이며, 이메일 주소는 minsu.kim@email.com입니다. 저희 회사의 대표 전화번호는 02-9876-5432입니다. 저는 1985년 3월 15일에 태어났고, 현재 38세입니다. 제 가족은 아내와 두 아이가 있습니다. 아내의 이름은 이영희이고, 그녀는 대학교에서 심리학을 전공했습니다. 아이들은 각각 7세와 5세이며, 학교에 다니고 있습니다. 저희 집 주소는 서울특별시 송파구 잠실동 456-78입니다. 최근에 저는 건강 검진을 받았고, 그 결과 고혈압 진단을 받았습니다. 이로 인해 주치의는 저에게 정기적인 운동과 건강한 식습관을 유지할 것을 권장했습니다. 주치의의 이름은 박지훈이며, 그의 병원은 서울 강서구에 위치한 강서메디컬입니다. 저는 여행을 좋아해서 매년 가족과 함께 해외여행을 계획합니다. 지난 여름에는 일본 도쿄에 갔었고, 그곳에서 가족과 함께 디즈니랜드를 방문했습니다. 그 여행에서 찍은 사진은 제 개인 소셜 미디어 계정에 업로드했습니다. 저는 IT 관련 분야에서 경력을 쌓아왔고, 현재 데이터 분석가로 일하고 있습니다. 제 직무는 데이터 수집, 분석 및 보고서를 작성하는 것입니다. 최근 프로젝트는 고객 행동 분석에 관한 것이며, 이를 통해 마케팅 전략을 개선하고 있습니다. 마지막으로, 저는 올해 새로운 기술을 배우기 위해 온라인 강좌에 등록했습니다. 관심 있는 분야는 인공지능과 머신러닝이며, 이를 통해 제 커리어를 발전시키고자 합니다.",
                "language": "en",
                "id": "1"
            }
        ]
    },
    "tasks":[{"taskId": "analyze 1","kind": "Healthcare","parameters": {"fhirVersion": "4.0.1"}}]}

###
GET {{$dotenv AZURE_LANGUAGE_ENDPOINT_URL}}/language/analyze-text/jobs/a113cc46-0832-4ebe-b0fa-ad63773ce683?api-version=2024-11-15-preview
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$dotenv AZURE_LANGUAGE_API_KEY}}
